### ISSUE TITLE
Add the posibility to configure the deployment with env vars 

### ISSUE THREAD

**Issue by matthieudiehr** [rhpds/bitwarden-k8s-secrets-manager#14]
I would like to be able to configure some of the well known env vars for the secret manager. For instance, i'd like to be able to do something like that in the kubernetes deployment:
```
env:
- name: BWS_SERVER_URL
  value: https://vault.bitwarden.eu
```

**Comment by 9strands** [comment]
@matthieudiehr - apologies for the delay, I've notified the developer of this PR and it's being checked.
