### ISSUE TITLE
Enhancement request - more examples please

### ISSUE THREAD

**Issue by mergwyn** [rhpds/bitwarden-k8s-secrets-manager#7]
Firstly, thanks for this great project. After installing with helm, I’ve successfully managed to sync my first secret using the `app-secret-key` example from the readme.  Where I’ve struggled is creating the second example `app-database-auth`, as despite looking at the code and unit tests I can’t mange to wrangle the correct yaml dict format into the Bitwarden secret.

Would it be possible to add examples into the readme for how to do this, possibly covering similar grounds to the unit tests?

**Comment by mergwyn** [comment]
I’ve got it working by using a format I would have sworn that I had tried already! Duh!
```
password: my_password
server: my_server
username: my_username
```

**Comment by 9strands** [comment]
Hi, @mergwyn - was there something in the docs that you think needed updating to clarify this?  We'd like to make it more clear if possible.

**Comment by mergwyn** [comment]
Thanks those examples would have help me.  In the unit tests you have examples such as :
  ```
"key": "dict_secret",
    "value": '''
        {
            "key00": "dict value",
            "key.with.periods": "value not nested",
            "nested": {"key01": "nested value"}
        }
```
You also have:
 ```
 def test_01(self):
        sources = {
            "value-pass-through": BitwardenSyncConfigSecretSource({
                "value": "value pass-through",
            }),
        }
        self.assertEqual(
            bitwarden_secrets.get_values(sources, bitwarden_projects),
            {"value-pass-through": "value pass-through"},
        )
```

It might just be me, but I didn' understand when you would used nested secrets, nor `value-pass-through`
