### ISSUE TITLE
Enhancement request - don’t always base64 encode

### ISSUE THREAD

**Issue by mergwyn** [rhpds/bitwarden-k8s-secrets-manager#8]
From my reading of the code it appears that the secret from BSM is always base64 encoded before creating the K8S secret. This works for most cases, but there are some circumstances when this is not appropriate.

One example is the argocd secret which is expected to be encoded by bcrypt: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-secret-yaml/

Would it be possible to encode with base64 as default but to selectively disable this for certain key:value pairs?

**Comment by jkupferer** [comment]
The kubernetes docs state: "The values for all keys in the data field have to be base64-encoded strings."
https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data

Attempting to create a secret with:

```
data:
  foo: bar
```

Produces the error:

```
Invalid value: "map[data:map[foo:bar]]": error decoding from json: illegal base64 data at input byte 0
```

So it seems like it must be base64 encoded...

But it occurs to me that there is another use case, which is that the value is already base64 encoded in bitwarden secrets manager and it should not be double-encoded.

**Comment by mergwyn** [comment]
Thanks.  I note the comment about the `data` type for secrets. That's a bit of a conumdrum as the argcod key is bcrypt encoded. This is how I create the secrets currently without using `stringData` rather than `data`:
```
kubectl -n argocd patch secret argocd-secret \
-p '{"stringData": {"admin.password": "'$(htpasswd -bnBC 10 "" ${password} | tr -d ':\n' | sed 's/$2y/$2a/')'", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'
```

Any suggestions?

**Comment by jkupferer** [comment]
Somewhere behind the scenes in the kubernetes api it translates from `stringData` to `data` by base64 encoding. If you get the secret after patching you should see `data` rather than `stringData` has been set.

For the bitwarden-k8s-secrets-manager the output of your htpasswd command pipeline would go into BWS as a secret (ex `ArgoCD Admin Password`) and then you could sync it to a k8s secret with something like:

```
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  data:
    admin.password:
      secret: ArgoCD Admin Password
```

But, maybe another feature request here as it seems you would want to patch an existing secret in this case rather than create and manage a new one?

**Comment by mergwyn** [comment]
Hi, many thanks for your super helpful response.  This is my bad, not appreciating that every time I run crypt it generates a different hash.  I do have a followup question if I may: is it possible to clear a key value (or set it to null)? The argo secret has a modification time which I wanted to clear when updating the secret.

(I don't think I have another use case using patch is just how I update the secret)
